### ISSUE TITLE
How to add an object with a key containing dots?

### ISSUE THREAD

**Issue by r3code** [hgourvest/superobject#12]
If I use an ip address 10.0.0.1 as key the SO parses it to multiple inner objects.
We found some workarounds [here](http://stackoverflow.com/questions/22652878/how-to-serialize-json-key-containing-dots-like-e-g-ip-address-with-superobjec/22652879#22652879) but what can you say as the author?

How should I encode the JSON below with SO?
```
{
 "10.0.6.3 | wifi0 | 6": {
  "date": 1455091545
 },
 "10.0.6.3 | LOOPBACK | 24": {
  "date": 1455091545
 }
}
```

**Comment by hgourvest** [comment]
using "AsObject" is the good syntax.

This is another way to build a complex object structure:
```
SO([
  '10.0.6.3 | wifi0 | 6', SO(['date', 1455091545]),
  '10.0.6.3 | LOOPBACK | 24', SO(['date', 1455091545]),
]);
```

**Comment by r3code** [comment]
But AsObject Fails with AV if original object is empty SO('{}'), so I can not use AsObject to add a new node with dotted key this way.

**Comment by hgourvest** [comment]
what you say makes no sense to me.

**Comment by r3code** [comment]
Ok. I'll provide an example source code later.

**Comment by r3code** [comment]
My solutions 
https://stackoverflow.com/questions/22652878/how-to-serialize-json-key-containing-dots-like-e-g-ip-address-with-superobjec
https://stackoverflow.com/questions/52203256/how-to-access-superobject-object-if-key-conatins-dots-e-g-ip-address
