### ISSUE TITLE
Settings node name with {} brackets fails.

### ISSUE THREAD

**Issue by ralfiii** [hgourvest/superobject#15]
Try the following code.
You'll see, the 2nd value disappears and leaves a memory leak.

     MySo:=SO('{}');
     MySo.S['ThisWorks']:='ok';
     MySo.S['{This one fails}']:='not ok';
     ShowMessage(MySo.AsJSon(True, False));

If I convert text with MySO:=SO(s) and s looks like this

     { "{foo}": {
       "Test": "Super"
      }
     }

everything works.

**Comment by hgourvest** [comment]
MySo.AsObject.S['{This not fails}']:='ok';

**Comment by ralfiii** [comment]
Super, thanks a lot.
One more question:
I actually need to build a object tree with root nodes having guids and normal values underneath, e.g.

     {
      "{guid1}": {
       "name11": "val11",
       "name12": "val12"
      },
      "{guid2}": {
       "name21": "val21",
       "name22": "val22"
      }
     }

How do I create such values?
     MySo.AsObject.S['{guid1}.name11']:='val11';
naturally creates a root node "{guid1}.name11" instead of a root node "{guid1}" with a value "name11" attached to it.
I only found that way:

     MySo2:=SO('{}');
     MySo2.S['name22']:='val22';
     MySo.AsObject.O['{guid1}']:=MySo2;

but isn't there a simpler way of doing that?
Thanks a lot!!!
Ralf

**Comment by ralfiii** [comment]
I just implemented it that way and actually that gives very nice, readable code, so I don't need a workaround anymore. Thanks!!!

**Comment by hgourvest** [comment]
you can use use SO function with a list of properties and values SO([p,v,p,v,...])
MySo.AsObject.O['{guid1}'] := SO(['name22', 'val22']);

you can also encapsulate this function
SO(['{guid}',SO(['name22', 'val22'])]);

**Comment by hermannoffen** [comment]
_I'm late to the party, I know._

But shouldn't it be sufficient to **wrap the identifier _string_ with quotation marks (U+0022)**, according to [ECMA-404](https://www.ecma-international.org/publications-and-standards/standards/ecma-404/) (chapters 6 & 9)?
