### ISSUE TITLE
Cannot properly escape literal string "\u"

### ISSUE THREAD

**Issue by svip** [hgourvest/superobject#28]
Consider the following code:

    try
      o := TSuperObject.ParseString('{"foo": "a\\u"', true);
      if o = nil then
        raise Exception.Create('Parse error');
      s := o.AsObject.S['foo'];
    except
      on E: Exception do begin
        ShowMessage(E.Message);
        exit;
      end;
    end;

  ShowMessage(s);

The expected result would be to see a message popup saying `a\u`, except `o` is `nil` and therefore I see the `Parse error`.

    {
      "foo": "a\\u"
    }

That JSON is valid, and superobject should be able to parse it.

[See also this question on StackOverflow](http://stackoverflow.com/questions/43043794/are-escape-sequences-escaped-in-order-or-simultaneously-in-json).

**Comment by dorward** [comment]
'{"foo": "a\\u"'

The } is missing from the object.

(And I don't know Pascal, but if \ is an escape character in a single quoted Pascal string, then the JSON will only have a single \ in it).

**Comment by svip** [comment]
Embarrassing.  You are right.  Adding the "}", fixed the issue.  I'm gonna close this issue.

(For the record, `\` is not an escape sequence in Pascal.)
