### ISSUE TITLE
support for delphi tokyo

### ISSUE THREAD

**Issue by singingprogrammer** [hgourvest/superobject#30]
Error  in compiling under delphi 10.2

[dcc32 Error] superobject.pas(6326): E2036 Variable required
[dcc32 Fatal Error] workplaceU.pas(11): F2063 Could not compile used unit 'superobject.pas'

**if CompareMem(@GetTypeData(TypeInfo).GUID, @soguid, SizeOf(TGUID)) then**
    begin
      if obj <> nil then
        TValue.Make(@obj, TypeInfo, Value) else
        begin
          o := TSuperObject.Create(stNull);
          TValue.Make(@o, TypeInfo, Value);
        end;
      Result := True;
    end else
      Result := False;

**Comment by Manuel1234567890** [comment]
This one works for me:

  ...
var
    o: ISuperObject;
    objGUID: TGuid;
  begin
    objGUID:= GetTypeData(TypeInfo).Guid;
    if CompareMem(@objGUID, @soguid, SizeOf(TGUID)) then
....

**Comment by singingprogrammer** [comment]
Yes. Manuel1234567890's solution solves the issue nicely.

Thanks for the input.
