### ISSUE TITLE
RTTI default value

### ISSUE THREAD

**Issue by psyfreaky** [hgourvest/superobject#7]
Let's say I use this object

  TMyClass = class
    fValue1: string;
    fValue2: Boolean;
  end;

and want to load it from json where some fields are missing, like this
MyClass.FromJson('{}', ctx);

fValue2 will throw an exception "Invalid object".
String value will be empty by default.

I have edited superobject for my purposes.
Is this behavior for purpose? Or can I set it to use default values instead of exception?

**Comment by psyfreaky** [comment]
It can be also solved with default attribute. That's probably the explanation.

**Comment by jheimtun** [comment]
Hi 

I do not use property declarations in my class. 
Can you please share some info on your superobject fix for parsing json with non-existing fields?

**Comment by psyfreaky** [comment]
I think it was something like this

`  TMyClass = class
  public
    [SODefault('789')]
    FTest: string;
  end;`

**Comment by psyfreaky** [comment]
I think it was something like this

```
TMyClass = class
  public
    [SODefault('789')]
    FTest: string;
  end;
```
