### ISSUE TITLE
Case of covert destruction of data (spaces in value names)

### ISSUE THREAD

**Issue by the-Arioch** [hgourvest/superobject#8]
```
var s: string; j: iSuperObject;
j := SO();
j.I['Value Name'] := 1;
s := j.AsJson;
```

Expected: '{"Value Name":1}'
Result: '{"Value":1}'

So, here we can see two problems at once.

1. the SuperObject lib destroys the data - it silently changes the value name without reporting error, t might even covertly overwrite another value!!! Another covert data loss scenario is when I load some JSON, edit it, and then push it back - destroying value with spaces during the process.

2. the SuperObject lib does not conform to JSON specs. According to http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf there are quotes:

2.1. `A string is a sequence of Unicode code points wrapped with quotation marks (U+0022). All characters may be
placed within the quotation marks except for the characters that must be escaped: quotation mark (U+0022),
reverse solidus (U+005C), and the control characters U+0000 to U+001F. ` - thus the Space $20 is not prohibited
2.2. `An object structure is represented as a pair of curly bracket tokens surrounding zero or more name/value pairs. A name is a string.`

While it is true that pseudo-JSON JavaScript objects can not contain spaces in value names - because they are not quoted and should be treated as valid JS identifiers, this should not apply to JSON-conformant quoted identifiers, and if SuperObject lib can not support JSON value names, then it should at least report it by signalling some error, rather than covertly destroy user-supplied data.

**Comment by hgourvest** [comment]
I hope I do not need an advocate...
for properties you just have write this:
j.AsObject.I['Value Name'] := 1;

the syntax you used is a "path helper" to access deep values in the tree, it is explained in the manual.

**Comment by the-Arioch** [comment]
> the syntax you used is a "path helper" to access deep values in the tree

While true, it changes little I think.

1. is it told in the manual that "path helper" can covertly access not the path specified by the user but some another path ?
2. is it told in the manual that "path helper" is not JSON-compliant ?
3. is it told in the manual that "path helper" considers space as something different and special-meaning?

And most general of all, I believe, 

4. The program is to do what it was asked for. IF the request was wrong and program can not implement it, then it should *explicitly refuse* to proceed with wrong request, rather than do some another random request instead of one specified.

Basically you said that the bug is not in the core TSuperObject property getter/setter but in the path helper, still a bug.

> I hope I do not need an advocate...

You would not for it was me responsible of the data that risked went missing, not you.

And the essence of FLOSS in a sense is that the mere fact of using it makes you a co-developer bearing all the practical rights but also *all the responsibilities* for that code.

So your role such a "Trial" is an "expert" or what it is called in France :-)

-------------

As a matter of fact, your readme is more like a scratchpad for yourself, for the person who already has deep knowledge of the library but might forge a detail or two.

Hopefully next year we would be able to discuss and extend it.

Truly, there are a lot of questions of newcomers who fail to understand how to do simple things.
And me including that readme left me few times with "what did he mean here?" confusion.

**Comment by the-Arioch** [comment]
found the following value name in the hierarchical storage: "D:Bool:1:CAN_DEREG"

* as you can see - it also does not comply with JavaScript identifiers requirements.
* and it complies with JSON requirement, just like "Value Name" does.

so basically there is no difference for the library whether that is a colon or a whitespace.

yet the helper works inconsistently corrupting one name and preserving another one, though no significant difference between them from both JS and JSON perspectives.
